In [1]:
import numpy as np

In [2]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

array

array([[ 1, -2,  3],
       [-4,  5, -6]])

In [3]:
abs_array = np.abs(array)

abs_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
flattened = array.flatten()

percentiles_flat = np.percentile(flattened, [25, 50, 75])

percentiles_flat

array([-3.5, -0.5,  2.5])

In [5]:
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)

percentiles_columns

array([[-2.75, -0.25, -3.75],
       [-1.5 ,  1.5 , -1.5 ],
       [-0.25,  3.25,  0.75]])

In [6]:
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

percentiles_rows

array([[-0.5, -5. ],
       [ 1. , -4. ],
       [ 2. ,  0.5]])

In [7]:
mean_flat = np.mean(flattened)
median_flat = np.median(flattened)
std_flat = np.std(flattened)

mean_flat, median_flat, std_flat

(-0.5, -0.5, 3.8622100754188224)

In [8]:
mean_cols = np.mean(array, axis=0)
median_cols = np.median(array, axis=0)
std_cols = np.std(array, axis=0)

mean_cols, median_cols, std_cols

(array([-1.5,  1.5, -1.5]), array([-1.5,  1.5, -1.5]), array([2.5, 3.5, 4.5]))

In [9]:
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

mean_rows, median_rows, std_rows

(array([ 0.66666667, -1.66666667]),
 array([ 1., -4.]),
 array([2.05480467, 4.78423336]))