In [1]:
import numpy as np

In [2]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

a

array([-1.8, -1.6, -0.5,  0.5,  1.6,  1.8,  3. ])

In [3]:
floor_values = np.floor(a)

floor_values

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [4]:
ceiling_values = np.ceil(a)

ceiling_values

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [5]:
truncated_values = np.trunc(a)

truncated_values

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [6]:
rounded_values = np.round(a)

rounded_values

array([-2., -2., -0.,  0.,  2.,  2.,  3.])