In [1]:
import numpy as np
from collections import defaultdict

In [2]:
# Generate 100 random integers between 0 and 99
data = np.random.randint(0, 100, 100)

data

array([77,  8, 67,  4, 27, 26,  7, 63, 82, 48, 75, 69, 35,  2, 83, 51, 64,
       31,  9, 99, 41, 52, 82, 51, 68, 82, 27, 51, 37, 65, 26, 73, 50, 66,
        8, 10, 38, 27, 94, 18, 69, 26,  5, 37, 99, 73, 89, 14, 99, 33, 37,
       72, 74, 14, 43, 65, 48, 76,  9, 85,  4, 47, 68, 11, 53,  0, 33, 28,
        6, 12, 90, 13,  1,  4, 58, 50, 87, 43, 46, 49, 37, 81, 22, 29, 64,
       91, 21, 26, 36, 23, 59, 47, 57, 18, 66, 51, 59,  9, 80, 53])

In [3]:
groups = defaultdict(list)

for value in data:
    group_key = value 
    groups[group_key].append(value)

groups

defaultdict(list,
            {77: [77],
             8: [8, 8],
             67: [67],
             4: [4, 4, 4],
             27: [27, 27, 27],
             26: [26, 26, 26, 26],
             7: [7],
             63: [63],
             82: [82, 82, 82],
             48: [48, 48],
             75: [75],
             69: [69, 69],
             35: [35],
             2: [2],
             83: [83],
             51: [51, 51, 51, 51],
             64: [64, 64],
             31: [31],
             9: [9, 9, 9],
             99: [99, 99, 99],
             41: [41],
             52: [52],
             68: [68, 68],
             37: [37, 37, 37, 37],
             65: [65, 65],
             73: [73, 73],
             50: [50, 50],
             66: [66, 66],
             10: [10],
             38: [38],
             94: [94],
             18: [18, 18],
             5: [5],
             89: [89],
             14: [14, 14],
             33: [33, 33],
             72: [72],
             74: [74],
 

In [4]:
# Find largest group size
max_length = max(len(group) for group in groups.values())


matrix = np.full((len(groups), max_length), np.nan)

# Fill matrix with grouped values
for row_index, key in enumerate(sorted(groups.keys())):
    matrix[row_index, :len(groups[key])] = groups[key]

matrix

array([[ 0., nan, nan, nan],
       [ 1., nan, nan, nan],
       [ 2., nan, nan, nan],
       [ 4.,  4.,  4., nan],
       [ 5., nan, nan, nan],
       [ 6., nan, nan, nan],
       [ 7., nan, nan, nan],
       [ 8.,  8., nan, nan],
       [ 9.,  9.,  9., nan],
       [10., nan, nan, nan],
       [11., nan, nan, nan],
       [12., nan, nan, nan],
       [13., nan, nan, nan],
       [14., 14., nan, nan],
       [18., 18., nan, nan],
       [21., nan, nan, nan],
       [22., nan, nan, nan],
       [23., nan, nan, nan],
       [26., 26., 26., 26.],
       [27., 27., 27., nan],
       [28., nan, nan, nan],
       [29., nan, nan, nan],
       [31., nan, nan, nan],
       [33., 33., nan, nan],
       [35., nan, nan, nan],
       [36., nan, nan, nan],
       [37., 37., 37., 37.],
       [38., nan, nan, nan],
       [41., nan, nan, nan],
       [43., 43., nan, nan],
       [46., nan, nan, nan],
       [47., 47., nan, nan],
       [48., 48., nan, nan],
       [49., nan, nan, nan],
       [50., 5

In [5]:
flat_clean = matrix[~np.isnan(matrix)]

flat_clean

array([ 0.,  1.,  2.,  4.,  4.,  4.,  5.,  6.,  7.,  8.,  8.,  9.,  9.,
        9., 10., 11., 12., 13., 14., 14., 18., 18., 21., 22., 23., 26.,
       26., 26., 26., 27., 27., 27., 28., 29., 31., 33., 33., 35., 36.,
       37., 37., 37., 37., 38., 41., 43., 43., 46., 47., 47., 48., 48.,
       49., 50., 50., 51., 51., 51., 51., 52., 53., 53., 57., 58., 59.,
       59., 63., 64., 64., 65., 65., 66., 66., 67., 68., 68., 69., 69.,
       72., 73., 73., 74., 75., 76., 77., 80., 81., 82., 82., 82., 83.,
       85., 87., 89., 90., 91., 94., 99., 99., 99.])