In [4]:
import numpy as np

In [5]:
def create_even_corner_matrix(n):
    
    matrix = np.random.randint(0, 50, size=(n, n))
    
    # Force all elements to be even
    matrix = matrix * 2
    
    return matrix

In [6]:
n = 5
matrix = create_even_corner_matrix(n)

print("Generated Matrix:\n")
print(matrix)

Generated Matrix:

[[64 78 44  6 34]
 [ 8  6 44 62 96]
 [92 96 98 88 28]
 [50 88 84 54 28]
 [ 2 72 40  4 80]]
