In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [3]:
addition = A + B
print("A + B =\n", addition)

A + B =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:
subtraction = A - B
print("A - B =\n", subtraction)

A - B =
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
